[profile.default]
  src = "src"
  out = "out"
  test = "test"
  libs = ["lib"]
  solc_version = "0.8.24"
  evm_version = "paris"
  optimizer = true
  optimizer_runs = 200
  fs_permissions = [{ access = "read", path = "./" }, { access = "read", path = "../" }]
  gas_reports = ["KRWS", "ZentEscrow", "ZentPayLink"]

[fmt]
  line_length = 120
  bracket_spacing = true
