name: contracts-ci

on:
  push:
    paths:
      - 'contract/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contract
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: Install deps
        run: forge install
      - name: Build
        run: forge build
      - name: Test
        run: forge test -vvv
